### ISSUE TITLE
bug: fix image in "Eligibility" section

### ISSUE THREAD

**Issue by anna4j** [anitab-org/events#12]
**Describe the bug**
In the eligibility section, the image on the right side of the text shows a white square on hover and hence a clean view isn't visible.
  

**Expected behavior**
A clear image should be visible with no change on hover or click.

**Screenshots**
![image](https://user-images.githubusercontent.com/43845261/90315195-1b27a600-df37-11ea-92e3-90ab24b220d0.png)

**Comment by Aditiwebd** [comment]
I want to work on this issue.Please assign it to me.

**Comment by Aaishpra** [comment]
@anna4j i would like to work on this

**Comment by Aaishpra** [comment]
Can someone assign this to me
