### ISSUE TITLE
Bug: Errors/typos in the description

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/events#15]
I found some errors/typos when going through the website.

1. resgistration -> registration
![events-1](https://user-images.githubusercontent.com/54268438/107839561-bc05f980-6dd2-11eb-81b2-437dec9555cd.JPG)

2. I'm sorry -> We're sorry (Also, I think this answer feels harsh, can we add something polite here) 
![events-2](https://user-images.githubusercontent.com/54268438/107839565-c1fbda80-6dd2-11eb-81cc-d8e06cf603ca.JPG)

3. Although the link is working still it should be corrected. 223070-questionS -> 223070-questions
<img width="403" alt="events-3" src="https://user-images.githubusercontent.com/54268438/107839568-c4f6cb00-6dd2-11eb-9bbc-77e2cc2c7f43.png">

**Comment by mayburgos** [comment]
Let's change number 2's text to: 

"We are unable to issue you a certificate if you do not meet our criteria."

**Comment by mayburgos** [comment]
This issue is approved. ✅

**Comment by prykdev** [comment]
if available can i work on this ?

**Comment by Rahulm2310** [comment]
Thanks @P-riyanka-prasad but there is already a PR for this.
