### ISSUE TITLE
Add instagram, zulip, medium and github logos(links) in the footer.

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/events#16]
We can add links to our instagram page, medium publication, and zulip and github in the footer.

1. Instagram : https://www.instagram.com/anitab_org/
2. Medium : https://medium.com/anitab-org-open-source
3. Zulip : https://anitab-org.zulipchat.com/
4. GitHub : https://github.com/anitab-org

**Comment by Rahulm2310** [comment]
@mayburgos Can you please confirm/approve this issue. If yes, can I be assigned this. Thanks 🙂

**Comment by mayburgos** [comment]
I don't think this is necessary right now. Our instagram has no posts. The rest are open source specific and I think our original intention was to create a generic AnitaB program with Open Source Hack.
