### ISSUE TITLE
Bug: Mismatch dates for OSH period under Rules and Timeline | URGENT

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/events#19]
### Describe the bug
The OSH periods stated under Rules and Timelines sections are different. Under Rules it's 1-31 Sep, under Timelines it's 1-30 April.

### To Reproduce
1. Go to https://anitab-org.github.io/events/open-source-hack/
2. Scroll down to Rules and check dates
3. Scroll down to Timeline and check dates
4. Notice the different OSH periods

### Expected behavior
The OSH periods should be the same across the site

### Screenshots
<img width="788" alt="Screen Shot 2021-03-15 at 11 01 27 am" src="https://user-images.githubusercontent.com/29667122/111089288-521e7280-857f-11eb-8566-5479b185e135.png">

<img width="761" alt="Screen Shot 2021-03-15 at 11 01 44 am" src="https://user-images.githubusercontent.com/29667122/111089294-56e32680-857f-11eb-9500-a6127e954061.png">

### Desktop (please complete the following information):
 - OS: macOS Catalina v10.15.7
 - Browser: Safari v 14.0.2

### Additional context
NA

**Comment by mtreacy002** [comment]
pinging @devkapilbansal , @annabauza and @17sushmita for transferring issue [# 262](https://github.com/anitab-org/anitab-org.github.io/issues/262) on Anita-org.github.io repo.

**Comment by devkapilbansal** [comment]
@mtreacy002 can you please label this issue too and assign this to the last assignee?? I am not able to triage this issue

**Comment by 17sushmita** [comment]
I would like to fix this

**Comment by mtreacy002** [comment]
I also seem to have no authority on this repo to assign contributor to this issue, @devkapilbansal, which is why I tagged @annabauza on this with hope she can assign this to @17sushmita who's been assigned on the other repo.

**Comment by 17sushmita** [comment]
Should I make the PR or wait for assignment?

**Comment by mtreacy002** [comment]
I believe you should wait for assignment from the maintainer of this repo. I'll try to ping them on zulip.

**Comment by devkapilbansal** [comment]
@anitab-org/admins Tagging other admins too here

**Comment by isabelcosta** [comment]
@17sushmita issue is yours :)
